### ISSUE TITLE
Interface of binary injector depends on whether we will have a single of two fields for trace context

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#11]
Current implementation of binary context inject/extract expects that entire SpanContext can be encoded in a single field:

https://github.com/bogdandrutu/openconsensus/blob/42f90bf8196cc1e3913510160cdfdc3995a7119d/api/src/main/java/openconsensus/context/propagation/BinaryFormat.java#L26-L33

However current proposal lists `traceparent` and `tracestate` as separate headers. See https://github.com/w3c/trace-context-binary/issues/7 with the proposal to change it

**Comment by tedsuo** [comment]
Since it has been resolved ghat we are going to follow https://github.com/w3c/trace-context-binary for our own interface, I am closing this issue for now.

**Comment by SergeyKanzhelev** [comment]
the issue is still there. Current spec expect that formatter can format context into a single bytes blob where spec is written for multiple fields.

**Comment by jmacd** [comment]
This is covered in #426, which raises several points about the need for more specification about binary propagation. These will be addressed in the next milestone.
